// Submodules extracted from the monolithic tests.rs.
// Each submodule lives in `tests/` and covers a focused test category.

#[cfg(feature = "agents")]
pub(crate) mod agent_bridge;
#[cfg(feature = "agents")]
pub(crate) mod agent_mcp;
#[cfg(feature = "agents")]
pub(crate) mod agent_pane;
pub(crate) mod app;
pub(crate) mod bounded_rule_extraction;
#[cfg(feature = "agents")]
pub(crate) mod builtin_tool_safeguards;
pub(crate) mod command_profiles;
pub(crate) mod command_trust;
pub(crate) mod commands;
pub(crate) mod edit_buffer;
pub(crate) mod edit_commands;
pub(crate) mod edit_goto;
pub(crate) mod edit_paste;
pub(crate) mod git;
pub(crate) mod helpers;
pub(crate) mod input;
pub(crate) mod keybindings;
pub(crate) mod keymap_config;
pub(crate) mod lsp_edits;
pub(crate) mod mandatory_confirm;
pub(crate) mod mcp_trust;
pub(crate) mod misc;
pub(crate) mod modes;
pub(crate) mod notifications;
pub(crate) mod permission_policy_matrix;
#[cfg(feature = "agents")]
pub(crate) mod persistent_deny;
pub(crate) mod render;
pub(crate) mod secrets_command;
pub(crate) mod secrets_e2e;
pub(crate) mod swift_motion;
pub(crate) mod trust_lifecycle;
pub(crate) mod trust_matrix;
pub(crate) mod trust_policy_effects;
pub(crate) mod trust_policy_foundation;
pub(crate) mod trust_rule_manager;
pub(crate) mod vlf_cache;
pub(crate) mod vlf_edit;
pub(crate) mod workspace_read_trust;
pub(crate) mod write_trust;
