//! OS secure-storage boundary and vault-key lifecycle (phase 2).
//!
//! The [`Keychain`] trait is the injectable boundary: tests use fakes, the
//! [`KeyringKeychain`] adapter talks to the real OS keychain. The vault key is
//! a random 256-bit value generated by the OS CSPRNG, persisted as stable
//! lowercase-hex text in the keychain entry `ee-secrets-v1`, and returned to
//! callers only after a successful write.

use zeroize::Zeroizing;

use super::SecretStoreError;

/// Keychain service name for secrets-store entries.
pub const KEYCHAIN_SERVICE: &str = "ee-secrets-v1";

/// Keychain account name: one deterministic account per current user-store
/// namespace. The namespace is the single default store until later phases
/// introduce more.
pub const KEYCHAIN_ACCOUNT: &str = "ee-secrets-v1";

/// OS secure-storage boundary for the vault key.
///
/// Implementations must never log, print, or return secret bytes inside error
/// text. [`KeyringKeychain`] is the real adapter; tests use fakes.
pub trait Keychain {
    /// Reads the entry for `service`/`account`, or `None` when absent.
    fn load(
        &self,
        service: &str,
        account: &str,
    ) -> Result<Option<Zeroizing<Vec<u8>>>, SecretStoreError>;

    /// Creates or replaces the entry for `service`/`account`.
    fn store(&self, service: &str, account: &str, value: &[u8]) -> Result<(), SecretStoreError>;
}

/// Real OS keychain adapter backed by the `keyring` crate.
pub struct KeyringKeychain;

impl Keychain for KeyringKeychain {
    fn load(
        &self,
        service: &str,
        account: &str,
    ) -> Result<Option<Zeroizing<Vec<u8>>>, SecretStoreError> {
        let entry = keyring::Entry::new(service, account)
            .map_err(|_| SecretStoreError::KeychainUnavailable)?;
        match entry.get_password() {
            Ok(text) => Ok(Some(Zeroizing::new(text.into_bytes()))),
            Err(keyring::Error::NoEntry) => Ok(None),
            Err(_) => Err(SecretStoreError::KeychainUnavailable),
        }
    }

    fn store(&self, service: &str, account: &str, value: &[u8]) -> Result<(), SecretStoreError> {
        let text = std::str::from_utf8(value).map_err(|_| SecretStoreError::KeychainCorruption)?;
        let entry = keyring::Entry::new(service, account)
            .map_err(|_| SecretStoreError::KeychainUnavailable)?;
        entry.set_password(text).map_err(|_| SecretStoreError::KeychainUnavailable)?;
        Ok(())
    }
}

/// Random 256-bit vault key, zeroized on drop.
///
/// Deliberately has no `Debug` impl and never appears in error messages.
pub struct VaultKey {
    key: Zeroizing<[u8; 32]>,
}

impl VaultKey {
    /// Loads the stored vault key without creating anything.
    ///
    /// `None` means no keychain entry exists. Malformed stored content is
    /// classified as [`SecretStoreError::KeychainCorruption`].
    pub(crate) fn load(keychain: &dyn Keychain) -> Result<Option<Self>, SecretStoreError> {
        match keychain.load(KEYCHAIN_SERVICE, KEYCHAIN_ACCOUNT)? {
            Some(encoded) => {
                let key = decode_hex32(&encoded).ok_or(SecretStoreError::KeychainCorruption)?;
                Ok(Some(Self { key: Zeroizing::new(key) }))
            }
            None => Ok(None),
        }
    }

    /// Loads the stored vault key, or generates one with the OS CSPRNG and
    /// persists it before returning.
    ///
    /// Key generation happens exactly once for a missing entry and never for
    /// an existing valid entry. Read or write failures propagate without
    /// exposing key bytes.
    pub(crate) fn load_or_create(keychain: &dyn Keychain) -> Result<Self, SecretStoreError> {
        if let Some(existing) = Self::load(keychain)? {
            return Ok(existing);
        }
        let key = random_bytes::<32>()?;
        let encoded = encode_hex32(&key);
        keychain.store(KEYCHAIN_SERVICE, KEYCHAIN_ACCOUNT, encoded.as_bytes())?;
        Ok(Self { key: Zeroizing::new(key) })
    }

    /// The raw key bytes, for phase-3 AEAD operations only.
    pub(crate) fn bytes(&self) -> &[u8; 32] {
        &self.key
    }
}

/// Fills a fixed-size buffer with OS CSPRNG bytes.
pub(crate) fn random_bytes<const N: usize>() -> Result<[u8; N], SecretStoreError> {
    use rand::TryRngCore as _;
    let mut bytes = [0u8; N];
    rand::rngs::OsRng
        .try_fill_bytes(&mut bytes)
        .map_err(|_| SecretStoreError::CspRngUnavailable)?;
    Ok(bytes)
}

/// Encodes 32 bytes as stable lowercase-hex text (64 chars) for keychain
/// persistence and vault metadata.
pub(crate) fn encode_hex32(bytes: &[u8; 32]) -> String {
    bytes.iter().map(|b| format!("{b:02x}")).collect()
}

/// Decodes stable lowercase-hex text into exactly 32 bytes.
///
/// `None` for any deviation: wrong length, uppercase hex, or non-hex bytes.
pub(crate) fn decode_hex32(text: &[u8]) -> Option<[u8; 32]> {
    if text.len() != 64 {
        return None;
    }
    let mut bytes = [0u8; 32];
    for (i, &[hi, lo]) in text.as_chunks::<2>().0.iter().enumerate() {
        bytes[i] = (hex_value(hi)? << 4) | hex_value(lo)?;
    }
    Some(bytes)
}

fn hex_value(byte: u8) -> Option<u8> {
    match byte {
        b'0'..=b'9' => Some(byte - b'0'),
        b'a'..=b'f' => Some(byte - b'a' + 10),
        _ => None,
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::secrets::test_support::{ScriptedKeychain, StoredKeychain};

    // ── Key encoding ─────────────────────────────────────────────────────────

    #[test]
    fn encode_is_stable_lowercase_hex() {
        let key = [0x00, 0x01, 0xab, 0xcd, 0xff, 0x10, 0x7f, 0x80];
        let mut full = [0u8; 32];
        full[..8].copy_from_slice(&key);
        let text = encode_hex32(&full);
        assert_eq!(text.len(), 64);
        assert_eq!(&text[..16], "0001abcdff107f80");
        assert!(text.bytes().all(|b| b.is_ascii_digit() || (b'a'..=b'f').contains(&b)));
        // Stable: same key, same text.
        assert_eq!(encode_hex32(&full), text);
    }

    #[test]
    fn decode_round_trips_and_rejects_malformed_content() {
        let key = [0xde, 0xad, 0xbe, 0xef, 0x42, 0x24, 0x99, 0x11, 0x00, 0xff];
        let mut full = [0u8; 32];
        full[..10].copy_from_slice(&key);
        assert_eq!(decode_hex32(encode_hex32(&full).as_bytes()), Some(full));

        // Wrong lengths.
        for bad in ["", "aa", &"a".repeat(63), &"a".repeat(65)] {
            assert_eq!(decode_hex32(bad.as_bytes()), None);
        }
        // Uppercase hex is not canonical, non-hex and non-ASCII bytes are corrupt.
        for bad in ["AA".repeat(32).as_str(), "zz".repeat(32).as_str(), "é".repeat(21).as_str()] {
            assert_eq!(decode_hex32(bad.as_bytes()), None);
        }
    }

    // ── Vault-key lifecycle ──────────────────────────────────────────────────

    #[test]
    fn key_is_generated_exactly_once_when_missing() {
        let keychain = StoredKeychain::new();
        let first = VaultKey::load_or_create(&keychain).expect("create");
        assert_eq!(keychain.load_calls(), 1);
        assert_eq!(keychain.store_calls(), 1, "persisted before returning");
        // Stored content is the stable hex text of the generated key.
        let stored = keychain.stored(KEYCHAIN_SERVICE, KEYCHAIN_ACCOUNT).expect("stored entry");
        assert_eq!(stored.len(), 64);
        assert_eq!(decode_hex32(&stored), Some(*first.bytes()));

        // Second load reuses the stored key: no new generation or write.
        let second = VaultKey::load_or_create(&keychain).expect("reuse");
        assert_eq!(keychain.load_calls(), 2);
        assert_eq!(keychain.store_calls(), 1, "never regenerated for an existing key");
        assert_eq!(second.bytes(), first.bytes());
    }

    #[test]
    fn existing_valid_key_is_never_regenerated() {
        let keychain = StoredKeychain::new();
        let existing = [0xab; 32];
        keychain.seed(KEYCHAIN_SERVICE, KEYCHAIN_ACCOUNT, encode_hex32(&existing).as_bytes());
        let loaded = VaultKey::load_or_create(&keychain).expect("load existing");
        assert_eq!(keychain.store_calls(), 0, "existing valid key: zero keychain writes");
        assert_eq!(loaded.bytes(), &existing);
    }

    #[test]
    fn plain_load_never_writes() {
        let keychain = StoredKeychain::new();
        assert!(VaultKey::load(&keychain).expect("no entry").is_none());
        assert_eq!(keychain.store_calls(), 0, "read-only load writes nothing");

        let existing = [0xcd; 32];
        keychain.seed(KEYCHAIN_SERVICE, KEYCHAIN_ACCOUNT, encode_hex32(&existing).as_bytes());
        let loaded = VaultKey::load(&keychain).expect("entry").expect("present");
        assert_eq!(loaded.bytes(), &existing);
        assert_eq!(keychain.store_calls(), 0);
    }

    #[test]
    fn malformed_stored_key_is_classified_as_corruption() {
        for bad in [&"zz".repeat(32)[..], &"AA".repeat(32)[..], "short"] {
            let keychain = StoredKeychain::new();
            keychain.seed(KEYCHAIN_SERVICE, KEYCHAIN_ACCOUNT, bad.as_bytes());
            assert!(
                matches!(
                    VaultKey::load_or_create(&keychain),
                    Err(SecretStoreError::KeychainCorruption)
                ),
                "content {bad:?} must be corruption"
            );
            assert_eq!(keychain.store_calls(), 0, "corrupt content is never overwritten");
        }
    }

    #[test]
    fn keychain_read_failure_propagates_without_side_effects() {
        let keychain =
            ScriptedKeychain::new(vec![Err(SecretStoreError::KeychainUnavailable)], vec![]);
        assert!(matches!(
            VaultKey::load_or_create(&keychain),
            Err(SecretStoreError::KeychainUnavailable)
        ));
        assert_eq!(keychain.load_calls(), 1);
        assert_eq!(keychain.store_calls(), 0, "no write after failed read");
    }

    #[test]
    fn keychain_write_failure_propagates_without_returning_key() {
        let keychain =
            ScriptedKeychain::new(vec![Ok(None)], vec![Err(SecretStoreError::KeychainUnavailable)]);
        assert!(matches!(
            VaultKey::load_or_create(&keychain),
            Err(SecretStoreError::KeychainUnavailable)
        ));
        assert_eq!(keychain.load_calls(), 1);
        assert_eq!(keychain.store_calls(), 1, "write attempted");
        // `load_or_create` returned Err, so no key can have escaped to a caller.
    }

    #[test]
    fn keyring_adapter_never_runs_in_unit_tests() {
        // Construction only: proves the adapter type is compilable without
        // ever contacting a platform keychain backend.
        let adapter = KeyringKeychain;
        assert!(std::mem::size_of_val(&adapter) == 0);
    }
}
