// GENERATED FILE - do not edit by hand.
// Regenerate with scripts/zed-catalog/sync.sh.

use std::collections::BTreeMap;

use crate::types::LanguageConfig;

/// Bundled LSP servers for Zed-documented languages.
pub(crate) fn bundled_zed_servers() -> Vec<(String, LanguageConfig)> {
    vec![
        (
            "ansible-language-server".to_string(),
            LanguageConfig {
                language_name: "Ansible".to_string(),
                start_command: "ansible-language-server".to_string(),
                start_arguments: vec!["--stdio".to_string()],
                extensions: vec![],
                filenames: vec![],
                supports_single_file: true,
                workspace_identifier: None,
                env: BTreeMap::new(),
                initialization_options: None,
            },
        ),
        (
            "astro-ls".to_string(),
            LanguageConfig {
                language_name: "Astro".to_string(),
                start_command: "astro-ls".to_string(),
                start_arguments: vec!["--stdio".to_string()],
                extensions: vec!["astro".to_string()],
                filenames: vec![],
                supports_single_file: true,
                workspace_identifier: Some("package.json".to_string()),
                env: BTreeMap::new(),
                initialization_options: None,
            },
        ),
        (
            "clojure-lsp".to_string(),
            LanguageConfig {
                language_name: "Clojure".to_string(),
                start_command: "clojure-lsp".to_string(),
                start_arguments: vec![],
                extensions: vec![
                    "clj".to_string(),
                    "cljs".to_string(),
                    "cljc".to_string(),
                    "edn".to_string(),
                ],
                filenames: vec![],
                supports_single_file: true,
                workspace_identifier: Some("deps.edn".to_string()),
                env: BTreeMap::new(),
                initialization_options: None,
            },
        ),
        (
            "dart".to_string(),
            LanguageConfig {
                language_name: "Dart".to_string(),
                start_command: "dart".to_string(),
                start_arguments: vec!["language-server".to_string(), "--protocol=lsp".to_string()],
                extensions: vec!["dart".to_string()],
                filenames: vec![],
                supports_single_file: false,
                workspace_identifier: Some("pubspec.yaml".to_string()),
                env: BTreeMap::new(),
                initialization_options: None,
            },
        ),
        (
            "elm-language-server".to_string(),
            LanguageConfig {
                language_name: "Elm".to_string(),
                start_command: "elm-language-server".to_string(),
                start_arguments: vec![],
                extensions: vec!["elm".to_string()],
                filenames: vec![],
                supports_single_file: true,
                workspace_identifier: Some("elm.json".to_string()),
                env: BTreeMap::new(),
                initialization_options: None,
            },
        ),
        (
            "erlang_ls".to_string(),
            LanguageConfig {
                language_name: "Erlang".to_string(),
                start_command: "erlang_ls".to_string(),
                start_arguments: vec![],
                extensions: vec!["erl".to_string(), "hrl".to_string()],
                filenames: vec![],
                supports_single_file: true,
                workspace_identifier: Some("rebar.config".to_string()),
                env: BTreeMap::new(),
                initialization_options: None,
            },
        ),
        (
            "jsonnet-language-server".to_string(),
            LanguageConfig {
                language_name: "Jsonnet".to_string(),
                start_command: "jsonnet-language-server".to_string(),
                start_arguments: vec![],
                extensions: vec!["jsonnet".to_string(), "libsonnet".to_string()],
                filenames: vec![],
                supports_single_file: true,
                workspace_identifier: None,
                env: BTreeMap::new(),
                initialization_options: None,
            },
        ),
        (
            "julia".to_string(),
            LanguageConfig {
                language_name: "Julia".to_string(),
                start_command: "julia".to_string(),
                start_arguments: vec![
                    "--startup-file=no".to_string(),
                    "--history-file=no".to_string(),
                    "-e".to_string(),
                    "using LanguageServer; runserver()".to_string(),
                ],
                extensions: vec!["jl".to_string()],
                filenames: vec![],
                supports_single_file: false,
                workspace_identifier: Some("Project.toml".to_string()),
                env: BTreeMap::new(),
                initialization_options: None,
            },
        ),
        (
            "lemminx".to_string(),
            LanguageConfig {
                language_name: "XML".to_string(),
                start_command: "lemminx".to_string(),
                start_arguments: vec![],
                extensions: vec!["xml".to_string(), "xsd".to_string(), "svg".to_string()],
                filenames: vec![],
                supports_single_file: true,
                workspace_identifier: None,
                env: BTreeMap::new(),
                initialization_options: None,
            },
        ),
        (
            "luau-lsp".to_string(),
            LanguageConfig {
                language_name: "Luau".to_string(),
                start_command: "luau-lsp".to_string(),
                start_arguments: vec![],
                extensions: vec!["luau".to_string()],
                filenames: vec![],
                supports_single_file: true,
                workspace_identifier: None,
                env: BTreeMap::new(),
                initialization_options: None,
            },
        ),
        (
            "millet".to_string(),
            LanguageConfig {
                language_name: "Standard ML".to_string(),
                start_command: "millet".to_string(),
                start_arguments: vec![],
                extensions: vec!["sml".to_string(), "sig".to_string()],
                filenames: vec![],
                supports_single_file: true,
                workspace_identifier: None,
                env: BTreeMap::new(),
                initialization_options: None,
            },
        ),
        (
            "nimlangserver".to_string(),
            LanguageConfig {
                language_name: "Nim".to_string(),
                start_command: "nimlangserver".to_string(),
                start_arguments: vec![],
                extensions: vec!["nim".to_string(), "nimble".to_string(), "nims".to_string()],
                filenames: vec![],
                supports_single_file: true,
                workspace_identifier: None,
                env: BTreeMap::new(),
                initialization_options: None,
            },
        ),
        (
            "prisma-language-server".to_string(),
            LanguageConfig {
                language_name: "Prisma".to_string(),
                start_command: "prisma-language-server".to_string(),
                start_arguments: vec!["--stdio".to_string()],
                extensions: vec!["prisma".to_string()],
                filenames: vec![],
                supports_single_file: true,
                workspace_identifier: None,
                env: BTreeMap::new(),
                initialization_options: None,
            },
        ),
        (
            "purescript-language-server".to_string(),
            LanguageConfig {
                language_name: "PureScript".to_string(),
                start_command: "purescript-language-server".to_string(),
                start_arguments: vec!["--stdio".to_string()],
                extensions: vec!["purs".to_string()],
                filenames: vec![],
                supports_single_file: false,
                workspace_identifier: Some("spago.yaml".to_string()),
                env: BTreeMap::new(),
                initialization_options: None,
            },
        ),
        (
            "r".to_string(),
            LanguageConfig {
                language_name: "R".to_string(),
                start_command: "R".to_string(),
                start_arguments: vec![
                    "--no-echo".to_string(),
                    "-e".to_string(),
                    "languageserver::run()".to_string(),
                ],
                extensions: vec!["r".to_string()],
                filenames: vec![],
                supports_single_file: true,
                workspace_identifier: None,
                env: BTreeMap::new(),
                initialization_options: None,
            },
        ),
        (
            "racket".to_string(),
            LanguageConfig {
                language_name: "Racket".to_string(),
                start_command: "racket".to_string(),
                start_arguments: vec!["--lib".to_string(), "racket-langserver".to_string()],
                extensions: vec!["rkt".to_string(), "scrbl".to_string()],
                filenames: vec![],
                supports_single_file: true,
                workspace_identifier: None,
                env: BTreeMap::new(),
                initialization_options: None,
            },
        ),
        (
            "regal".to_string(),
            LanguageConfig {
                language_name: "Rego".to_string(),
                start_command: "regal".to_string(),
                start_arguments: vec!["lsp".to_string()],
                extensions: vec!["rego".to_string()],
                filenames: vec![],
                supports_single_file: true,
                workspace_identifier: None,
                env: BTreeMap::new(),
                initialization_options: None,
            },
        ),
        (
            "terraform-ls".to_string(),
            LanguageConfig {
                language_name: "Terraform".to_string(),
                start_command: "terraform-ls".to_string(),
                start_arguments: vec![],
                extensions: vec!["tf".to_string(), "tfvars".to_string(), "tofu".to_string()],
                filenames: vec![],
                supports_single_file: true,
                workspace_identifier: None,
                env: BTreeMap::new(),
                initialization_options: None,
            },
        ),
    ]
}

/// Language -> server attachment routing for Zed-documented languages.
pub(crate) fn bundled_zed_routing() -> Vec<(String, Vec<String>)> {
    vec![
        ("ansible-language-server".to_string(), vec!["ansible-language-server".to_string()]),
        ("astro-ls".to_string(), vec!["astro-ls".to_string()]),
        ("clojure-lsp".to_string(), vec!["clojure-lsp".to_string()]),
        ("dart".to_string(), vec!["dart".to_string()]),
        ("elm-language-server".to_string(), vec!["elm-language-server".to_string()]),
        ("erlang_ls".to_string(), vec!["erlang_ls".to_string()]),
        ("jsonnet-language-server".to_string(), vec!["jsonnet-language-server".to_string()]),
        ("julia".to_string(), vec!["julia".to_string()]),
        ("lemminx".to_string(), vec!["lemminx".to_string()]),
        ("luau-lsp".to_string(), vec!["luau-lsp".to_string()]),
        ("millet".to_string(), vec!["millet".to_string()]),
        ("nimlangserver".to_string(), vec!["nimlangserver".to_string()]),
        ("prisma-language-server".to_string(), vec!["prisma-language-server".to_string()]),
        ("purescript-language-server".to_string(), vec!["purescript-language-server".to_string()]),
        ("r".to_string(), vec!["r".to_string()]),
        ("racket".to_string(), vec!["racket".to_string()]),
        ("regal".to_string(), vec!["regal".to_string()]),
        ("terraform-ls".to_string(), vec!["terraform-ls".to_string()]),
        ("docker".to_string(), vec!["dockerfile".to_string()]),
        ("gleam".to_string(), vec!["gleam".to_string()]),
        ("just".to_string(), vec!["just".to_string()]),
        ("kotlin".to_string(), vec!["kotlin-language-server".to_string()]),
        ("lua".to_string(), vec!["lua-language-server".to_string()]),
        ("ocaml".to_string(), vec!["ocamllsp".to_string()]),
        ("opentofu".to_string(), vec!["terraform-ls".to_string()]),
        ("svelte".to_string(), vec!["svelteserver".to_string()]),
        ("terraform".to_string(), vec!["terraform-ls".to_string()]),
        ("toml".to_string(), vec!["taplo".to_string()]),
        ("vue".to_string(), vec!["vue-language-server".to_string()]),
        ("zig".to_string(), vec!["zls".to_string()]),
    ]
}
